export interface SectionData {
  id: string;
  sectionId: string;
  title: string;
  note: string;
  sortOrder?: number;
  metadata?: Record<string, unknown>;
}

export const defaultSections: SectionData[] = [
  {
    id: "work",
    sectionId: "work",
    title: "Previous Work",
    note: "Public links and embeds, arranged like a clean proof section.",
    sortOrder: 0,
  },
  {
    id: "reels",
    sectionId: "reels",
    title: "Photo Reel",
    note: "A quick sample of my work in a scrolling reel format.",
    sortOrder: 1,
    metadata: { layout: "reels" },
  },
  {
    id: "companies",
    sectionId: "companies",
    title: "Companies I've Worked With",
    note: "Brands, networks, and platforms I've collaborated with.",
    sortOrder: 2,
  },
  {
    id: "testimonials",
    sectionId: "testimonials",
    title: "Testimonials",
    note: "Client words presented as collectible cards rather than a flat carousel.",
    sortOrder: 3,
    metadata: { layout: "testimonials" },
  },
  {
    id: "fan",
    sectionId: "fan",
    title: "Featured Projects",
    note: "Fan-layout showcase of standout work. Hover to focus any card.",
    sortOrder: 4,
    metadata: { layout: "fan" },
  },
];

export const sections = defaultSections;

export interface CardData {
  id: string;
  section: string;
  type: string;
  title: string;
  description: string;
  url: string;
  imageUrl: string;
  useCustomThumbnail: boolean;
  embed: boolean;
  size: string;
  sortOrder: number;
  metadata?: Record<string, unknown>;
}

export const defaultCards: CardData[] = [
  // ── Previous Work: YouTube ──
  {
    id: "seed-work-1",
    section: "work",
    type: "youtube",
    title: "Bihar Vote Adhikar Yatra",
    description: "Coverage of the Bihar Vote Adhikar Yatra campaign — ground reporting and host-led narration.",
    url: "https://youtu.be/LND5_8PPcF8",
    imageUrl: "",
    useCustomThumbnail: false,
    embed: true,
    size: "standard",
    sortOrder: 1,
    metadata: { aspectRatio: "16:9" },
  },
  {
    id: "seed-work-2",
    section: "work",
    type: "youtube",
    title: "Delhi Yamuna Cleaning 2025",
    description: "Latest news coverage on the Delhi Yamuna cleaning drive — voice-over and scripting.",
    url: "https://youtu.be/flTBGkXaRrg",
    imageUrl: "",
    useCustomThumbnail: false,
    embed: true,
    size: "standard",
    sortOrder: 2,
    metadata: { aspectRatio: "16:9" },
  },
  {
    id: "seed-work-3",
    section: "work",
    type: "youtube",
    title: "Prashant Kishor: The Untold Story",
    description: "In-depth feature on Prashant Kishor's political journey — narration and production.",
    url: "https://www.youtube.com/watch?v=Blpr8w-40_k",
    imageUrl: "",
    useCustomThumbnail: false,
    embed: true,
    size: "standard",
    sortOrder: 3,
    metadata: { aspectRatio: "16:9" },
  },

  // ── Companies ──
  {
    id: "seed-company-1",
    section: "companies",
    type: "company",
    title: "Piyush Goel YouTube",
    description: "Voice-over demos, showreels, and hosted content on YouTube.",
    url: "https://www.youtube.com/channel/UC43qCBEfmy-wouPmYlLSpIg",
    imageUrl: "",
    useCustomThumbnail: false,
    embed: false,
    size: "80",
    sortOrder: 10,
  },
  {
    id: "seed-company-2",
    section: "companies",
    type: "company",
    title: "Kuku FM",
    description: "Voice artist for audiobooks and original audio series.",
    url: "https://kukufm.com",
    imageUrl: "",
    useCustomThumbnail: false,
    embed: false,
    size: "80",
    sortOrder: 11,
  },
  {
    id: "seed-company-3",
    section: "companies",
    type: "company",
    title: "Pocket FM",
    description: "Narrated and performed in multiple audio series.",
    url: "https://pocketfm.com",
    imageUrl: "",
    useCustomThumbnail: false,
    embed: false,
    size: "80",
    sortOrder: 12,
  },
  {
    id: "seed-company-4",
    section: "companies",
    type: "company",
    title: "Story TV",
    description: "Voice acting for animated and hosted content.",
    url: "https://storytv.in",
    imageUrl: "",
    useCustomThumbnail: false,
    embed: false,
    size: "80",
    sortOrder: 13,
  },
  {
    id: "seed-testimonial-1",
    section: "testimonials",
    type: "testimonial",
    title: "Aarav Mehta",
    description: "Piyush's voice is exactly what we needed — warm and easy to trust. He got the script right on the first try and sent everything back early. Honestly one of the smoothest collaborations we've had.",
    url: "",
    imageUrl: "",
    useCustomThumbnail: false,
    embed: false,
    size: "standard",
    sortOrder: 14,
    metadata: {
      role: "Creative Lead",
      company: "YouTube Partner",
      rating: 5,
      projectName: "Brand film rollout",
      service: "Voiceover and hosting",
      tags: "Narration, Delivery",
      accent: "linear-gradient(135deg, #0c1445 0%, #2563eb 60%, #60a5fa 100%)",
      quotePreview: "Warm voice, easy to work with, delivered early.",
    },
  },
  {
    id: "seed-testimonial-2",
    section: "testimonials",
    type: "testimonial",
    title: "Sara Khan",
    description: "I sent Piyush a rough brief and he just got it — no back and forth needed. The voice matched our brand better than I expected, and he turned it around fast. Would book him again without thinking twice.",
    url: "",
    imageUrl: "",
    useCustomThumbnail: false,
    embed: false,
    size: "standard",
    sortOrder: 15,
    metadata: {
      role: "Manager",
      company: "Pocket FM",
      rating: 5,
      projectName: "Social campaign package",
      service: "Script + hosting",
      tags: "Campaign, Social",
      accent: "linear-gradient(135deg, #3b0764 0%, #7c3aed 60%, #a78bfa 100%)",
      quotePreview: "Got our brief right away, fast turnaround.",
    },
  },
  {
    id: "seed-testimonial-3",
    section: "testimonials",
    type: "testimonial",
    title: "Rohan Das",
    description: "The way Piyush paced our audio series felt completely natural, like someone telling you a story instead of reading a script. We didn't ask for a single revision — that almost never happens.",
    url: "",
    imageUrl: "",
    useCustomThumbnail: false,
    embed: false,
    size: "standard",
    sortOrder: 16,
    metadata: {
      role: "Content Head",
      company: "Kuku FM",
      rating: 5,
      projectName: "Launch narrative",
      service: "Narration",
      tags: "Narrative, Voice",
      accent: "linear-gradient(135deg, #022c22 0%, #059669 60%, #34d399 100%)",
      quotePreview: "Natural pacing, zero revisions needed.",
    },
  },
  {
    id: "seed-testimonial-4",
    section: "testimonials",
    type: "testimonial",
    title: "Nisha Verma",
    description: "We wanted a voice that sounded confident but still like a real person, not an ad. Piyush nailed that balance, and we actually saw our engagement go up after the campaign launched. He's on our regular roster now.",
    url: "",
    imageUrl: "",
    useCustomThumbnail: false,
    embed: false,
    size: "standard",
    sortOrder: 17,
    metadata: {
      role: "Producer",
      company: "Story TV",
      rating: 5,
      projectName: "Ad campaign voiceover",
      service: "Voice acting",
      tags: "Advertising, Voice",
      accent: "linear-gradient(135deg, #7c2d12 0%, #ea580c 60%, #fbbf24 100%)",
      quotePreview: "Confident but real, engagement went up after launch.",
    },
  },
  {
    id: "seed-testimonial-5",
    section: "testimonials",
    type: "testimonial",
    title: "Vikram Mehta",
    description: "What stood out is how easily Piyush switches styles — serious for a news segment, relaxed for a reel, without it ever feeling forced. He's careful with details too, which saves us a ton of back and forth.",
    url: "",
    imageUrl: "",
    useCustomThumbnail: false,
    embed: false,
    size: "standard",
    sortOrder: 18,
    metadata: {
      role: "Director",
      company: "Radio City",
      rating: 5,
      projectName: "Radio show hosting",
      service: "Hosting",
      tags: "Radio, Hosting",
      accent: "linear-gradient(135deg, #831843 0%, #db2777 60%, #f472b6 100%)",
      quotePreview: "Switches styles easily, careful with details.",
    },
  },

  // ── Featured Projects (Fan Layout) ──
  {
    id: "seed-fan-1",
    section: "fan",
    type: "fan",
    title: "Portal",
    description: "",
    url: "",
    imageUrl: "https://picsum.photos/seed/portal/400/520",
    useCustomThumbnail: false,
    embed: false,
    size: "standard",
    sortOrder: 17,
    metadata: { tag: "Web App", score: 4.9 },
  },
  {
    id: "seed-fan-2",
    section: "fan",
    type: "fan",
    title: "Meridian",
    description: "",
    url: "",
    imageUrl: "https://picsum.photos/seed/meridian/400/520",
    useCustomThumbnail: false,
    embed: false,
    size: "standard",
    sortOrder: 18,
    metadata: { tag: "Brand Identity", score: 4.7 },
  },
  {
    id: "seed-fan-3",
    section: "fan",
    type: "fan",
    title: "Aether",
    description: "",
    url: "",
    imageUrl: "https://picsum.photos/seed/aether/400/520",
    useCustomThumbnail: false,
    embed: false,
    size: "standard",
    sortOrder: 19,
    metadata: { tag: "UI/UX Design", score: 4.8 },
  },
  {
    id: "seed-fan-4",
    section: "fan",
    type: "fan",
    title: "Cascade",
    description: "",
    url: "",
    imageUrl: "https://picsum.photos/seed/cascade/400/520",
    useCustomThumbnail: false,
    embed: false,
    size: "standard",
    sortOrder: 20,
    metadata: { tag: "Mobile App", score: 4.5 },
  },
  {
    id: "seed-fan-5",
    section: "fan",
    type: "fan",
    title: "Vertex",
    description: "",
    url: "",
    imageUrl: "https://picsum.photos/seed/vertex/400/520",
    useCustomThumbnail: false,
    embed: false,
    size: "standard",
    sortOrder: 21,
    metadata: { tag: "Dashboard", score: 4.6 },
  },

  // ── Reel Images ──
  { id: "seed-reel-1", section: "reels", type: "reel", title: "", description: "", url: "", imageUrl: "https://picsum.photos/seed/reel01/400/520", useCustomThumbnail: false, embed: false, size: "standard", sortOrder: 22 },
  { id: "seed-reel-2", section: "reels", type: "reel", title: "", description: "", url: "", imageUrl: "https://picsum.photos/seed/reel02/400/520", useCustomThumbnail: false, embed: false, size: "standard", sortOrder: 23 },
  { id: "seed-reel-3", section: "reels", type: "reel", title: "", description: "", url: "", imageUrl: "https://picsum.photos/seed/reel03/400/520", useCustomThumbnail: false, embed: false, size: "standard", sortOrder: 24 },
  { id: "seed-reel-4", section: "reels", type: "reel", title: "", description: "", url: "", imageUrl: "https://picsum.photos/seed/reel04/400/520", useCustomThumbnail: false, embed: false, size: "standard", sortOrder: 25 },
  { id: "seed-reel-5", section: "reels", type: "reel", title: "", description: "", url: "", imageUrl: "https://picsum.photos/seed/reel05/400/520", useCustomThumbnail: false, embed: false, size: "standard", sortOrder: 26 },
  { id: "seed-reel-6", section: "reels", type: "reel", title: "", description: "", url: "", imageUrl: "https://picsum.photos/seed/reel06/400/520", useCustomThumbnail: false, embed: false, size: "standard", sortOrder: 27 },
  { id: "seed-reel-7", section: "reels", type: "reel", title: "", description: "", url: "", imageUrl: "https://picsum.photos/seed/reel07/400/520", useCustomThumbnail: false, embed: false, size: "standard", sortOrder: 28 },
  { id: "seed-reel-8", section: "reels", type: "reel", title: "", description: "", url: "", imageUrl: "https://picsum.photos/seed/reel08/400/520", useCustomThumbnail: false, embed: false, size: "standard", sortOrder: 29 },
  { id: "seed-reel-9", section: "reels", type: "reel", title: "", description: "", url: "", imageUrl: "https://picsum.photos/seed/reel09/400/520", useCustomThumbnail: false, embed: false, size: "standard", sortOrder: 30 },
  { id: "seed-reel-10", section: "reels", type: "reel", title: "", description: "", url: "", imageUrl: "https://picsum.photos/seed/reel10/400/520", useCustomThumbnail: false, embed: false, size: "standard", sortOrder: 31 },
  { id: "seed-reel-11", section: "reels", type: "reel", title: "", description: "", url: "", imageUrl: "https://picsum.photos/seed/reel11/400/520", useCustomThumbnail: false, embed: false, size: "standard", sortOrder: 32 },
  { id: "seed-reel-12", section: "reels", type: "reel", title: "", description: "", url: "", imageUrl: "https://picsum.photos/seed/reel12/400/520", useCustomThumbnail: false, embed: false, size: "standard", sortOrder: 33 },
  { id: "seed-reel-13", section: "reels", type: "reel", title: "", description: "", url: "", imageUrl: "https://picsum.photos/seed/reel13/400/520", useCustomThumbnail: false, embed: false, size: "standard", sortOrder: 34 },
  { id: "seed-reel-14", section: "reels", type: "reel", title: "", description: "", url: "", imageUrl: "https://picsum.photos/seed/reel14/400/520", useCustomThumbnail: false, embed: false, size: "standard", sortOrder: 35 },
  { id: "seed-reel-15", section: "reels", type: "reel", title: "", description: "", url: "", imageUrl: "https://picsum.photos/seed/reel15/400/520", useCustomThumbnail: false, embed: false, size: "standard", sortOrder: 36 },
  { id: "seed-reel-16", section: "reels", type: "reel", title: "", description: "", url: "", imageUrl: "https://picsum.photos/seed/reel16/400/520", useCustomThumbnail: false, embed: false, size: "standard", sortOrder: 37 },
  { id: "seed-reel-17", section: "reels", type: "reel", title: "", description: "", url: "", imageUrl: "https://picsum.photos/seed/reel17/400/520", useCustomThumbnail: false, embed: false, size: "standard", sortOrder: 38 },
  { id: "seed-reel-18", section: "reels", type: "reel", title: "", description: "", url: "", imageUrl: "https://picsum.photos/seed/reel18/400/520", useCustomThumbnail: false, embed: false, size: "standard", sortOrder: 39 },
  { id: "seed-reel-19", section: "reels", type: "reel", title: "", description: "", url: "", imageUrl: "https://picsum.photos/seed/reel19/400/520", useCustomThumbnail: false, embed: false, size: "standard", sortOrder: 40 },
  { id: "seed-reel-20", section: "reels", type: "reel", title: "", description: "", url: "", imageUrl: "https://picsum.photos/seed/reel20/400/520", useCustomThumbnail: false, embed: false, size: "standard", sortOrder: 41 },
  { id: "seed-reel-21", section: "reels", type: "reel", title: "", description: "", url: "", imageUrl: "https://picsum.photos/seed/reel21/400/520", useCustomThumbnail: false, embed: false, size: "standard", sortOrder: 42 },
  { id: "seed-reel-22", section: "reels", type: "reel", title: "", description: "", url: "", imageUrl: "https://picsum.photos/seed/reel22/400/520", useCustomThumbnail: false, embed: false, size: "standard", sortOrder: 43 },
  { id: "seed-reel-23", section: "reels", type: "reel", title: "", description: "", url: "", imageUrl: "https://picsum.photos/seed/reel23/400/520", useCustomThumbnail: false, embed: false, size: "standard", sortOrder: 44 },
  { id: "seed-reel-24", section: "reels", type: "reel", title: "", description: "", url: "", imageUrl: "https://picsum.photos/seed/reel24/400/520", useCustomThumbnail: false, embed: false, size: "standard", sortOrder: 45 },
  { id: "seed-reel-25", section: "reels", type: "reel", title: "", description: "", url: "", imageUrl: "https://picsum.photos/seed/reel25/400/520", useCustomThumbnail: false, embed: false, size: "standard", sortOrder: 46 },
  { id: "seed-reel-26", section: "reels", type: "reel", title: "", description: "", url: "", imageUrl: "https://picsum.photos/seed/reel26/400/520", useCustomThumbnail: false, embed: false, size: "standard", sortOrder: 47 },
  { id: "seed-reel-27", section: "reels", type: "reel", title: "", description: "", url: "", imageUrl: "https://picsum.photos/seed/reel27/400/520", useCustomThumbnail: false, embed: false, size: "standard", sortOrder: 48 },
  { id: "seed-reel-28", section: "reels", type: "reel", title: "", description: "", url: "", imageUrl: "https://picsum.photos/seed/reel28/400/520", useCustomThumbnail: false, embed: false, size: "standard", sortOrder: 49 },
  { id: "seed-reel-29", section: "reels", type: "reel", title: "", description: "", url: "", imageUrl: "https://picsum.photos/seed/reel29/400/520", useCustomThumbnail: false, embed: false, size: "standard", sortOrder: 50 },
  { id: "seed-reel-30", section: "reels", type: "reel", title: "", description: "", url: "", imageUrl: "https://picsum.photos/seed/reel30/400/520", useCustomThumbnail: false, embed: false, size: "standard", sortOrder: 51 },
];
