export interface SectionData {
  id: string;
  sectionId: string;
  title: string;
  note: string;
  sortOrder?: number;
  metadata?: Record<string, unknown>;
}

export const defaultSections: SectionData[] = [
  {
    id: "work",
    sectionId: "work",
    title: "Previous Work",
    note: "Public links and embeds, arranged like a clean proof section.",
    sortOrder: 0,
  },
  {
    id: "companies",
    sectionId: "companies",
    title: "Companies I've Worked With",
    note: "Brands, networks, and platforms I've collaborated with.",
    sortOrder: 1,
  },
  {
    id: "testimonials",
    sectionId: "testimonials",
    title: "Testimonials",
    note: "Client words presented as collectible cards rather than a flat carousel.",
    sortOrder: 2,
    metadata: { layout: "testimonials" },
  },
  {
    id: "social",
    sectionId: "social",
    title: "Social Work",
    note: "Personality-led clips and host moments.",
    sortOrder: 3,
  },
  {
    id: "fan",
    sectionId: "fan",
    title: "Featured Projects",
    note: "Fan-layout showcase of standout work. Hover to focus any card.",
    sortOrder: 4,
    metadata: { layout: "fan" },
  },
  {
    id: "reels",
    sectionId: "reels",
    title: "Photo Reel",
    note: "A quick sample of my work in a scrolling reel format.",
    sortOrder: 5,
    metadata: { layout: "reels" },
  },
];

export const sections = defaultSections;

export interface CardData {
  id: string;
  section: string;
  type: string;
  title: string;
  description: string;
  url: string;
  imageUrl: string;
  useCustomThumbnail: boolean;
  embed: boolean;
  size: string;
  sortOrder: number;
  metadata?: Record<string, unknown>;
}

export const defaultCards: CardData[] = [
  // ── Previous Work: YouTube ──
  {
    id: "seed-work-1",
    section: "work",
    type: "youtube",
    title: "Bihar Vote Adhikar Yatra",
    description: "Coverage of the Bihar Vote Adhikar Yatra campaign — ground reporting and host-led narration.",
    url: "https://youtu.be/LND5_8PPcF8",
    imageUrl: "",
    useCustomThumbnail: false,
    embed: true,
    size: "standard",
    sortOrder: 1,
    metadata: { aspectRatio: "16:9" },
  },
  {
    id: "seed-work-2",
    section: "work",
    type: "youtube",
    title: "Delhi Yamuna Cleaning 2025",
    description: "Latest news coverage on the Delhi Yamuna cleaning drive — voice-over and scripting.",
    url: "https://youtu.be/flTBGkXaRrg",
    imageUrl: "",
    useCustomThumbnail: false,
    embed: true,
    size: "standard",
    sortOrder: 2,
    metadata: { aspectRatio: "16:9" },
  },
  {
    id: "seed-work-3",
    section: "work",
    type: "youtube",
    title: "Prashant Kishor: The Untold Story",
    description: "In-depth feature on Prashant Kishor's political journey — narration and production.",
    url: "https://www.youtube.com/watch?v=Blpr8w-40_k",
    imageUrl: "",
    useCustomThumbnail: false,
    embed: true,
    size: "standard",
    sortOrder: 3,
    metadata: { aspectRatio: "16:9" },
  },

  // ── Social: Instagram Reels ──
  {
    id: "seed-social-1",
    section: "social",
    type: "instagram",
    title: "Kailash Kher — Host Moment",
    description: "Personality-led reel featuring Kailash Kher — host segment with engaging storytelling.",
    url: "https://www.instagram.com/reel/CkngjKmgWNa/",
    imageUrl: "",
    useCustomThumbnail: false,
    embed: true,
    size: "wide",
    sortOrder: 5,
    metadata: { aspectRatio: "9:16" },
  },
  {
    id: "seed-social-2",
    section: "social",
    type: "instagram",
    title: "Lohri Special",
    description: "Festival special with guest appearance — radio-style hosting on social.",
    url: "https://www.instagram.com/reel/CnWVegXpUHA/",
    imageUrl: "",
    useCustomThumbnail: false,
    embed: true,
    size: "wide",
    sortOrder: 6,
    metadata: { aspectRatio: "9:16" },
  },
  {
    id: "seed-social-3",
    section: "social",
    type: "instagram",
    title: "Special Guest Feature",
    description: "On-camera host moment with a special guest — quick, engaging social content.",
    url: "https://www.instagram.com/reel/Cft-bi1AcYz/",
    imageUrl: "",
    useCustomThumbnail: false,
    embed: true,
    size: "wide",
    sortOrder: 7,
    metadata: { aspectRatio: "9:16" },
  },
  {
    id: "seed-social-4",
    section: "social",
    type: "instagram",
    title: "IG TV — Segment 1",
    description: "Long-form IG TV content — host-led storytelling and audience engagement.",
    url: "https://www.instagram.com/p/CdzvTsxoZKL/",
    imageUrl: "",
    useCustomThumbnail: false,
    embed: true,
    size: "standard",
    sortOrder: 8,
    metadata: { aspectRatio: "16:9" },
  },
  {
    id: "seed-social-5",
    section: "social",
    type: "instagram",
    title: "IG TV — Segment 2",
    description: "Another IG TV feature with on-camera hosting and creator-led narrative.",
    url: "https://www.instagram.com/p/CXlWdTBpXmb/",
    imageUrl: "",
    useCustomThumbnail: false,
    embed: true,
    size: "standard",
    sortOrder: 9,
    metadata: { aspectRatio: "16:9" },
  },

  // ── Companies ──
  {
    id: "seed-company-1",
    section: "companies",
    type: "company",
    title: "Piyush Goel YouTube",
    description: "Voice-over demos, showreels, and hosted content on YouTube.",
    url: "https://www.youtube.com/channel/UC43qCBEfmy-wouPmYlLSpIg",
    imageUrl: "",
    useCustomThumbnail: false,
    embed: false,
    size: "80",
    sortOrder: 10,
  },
  {
    id: "seed-company-2",
    section: "companies",
    type: "company",
    title: "Kuku FM",
    description: "Voice artist for audiobooks and original audio series.",
    url: "https://kukufm.com",
    imageUrl: "",
    useCustomThumbnail: false,
    embed: false,
    size: "80",
    sortOrder: 11,
  },
  {
    id: "seed-company-3",
    section: "companies",
    type: "company",
    title: "Pocket FM",
    description: "Narrated and performed in multiple audio series.",
    url: "https://pocketfm.com",
    imageUrl: "",
    useCustomThumbnail: false,
    embed: false,
    size: "80",
    sortOrder: 12,
  },
  {
    id: "seed-company-4",
    section: "companies",
    type: "company",
    title: "Story TV",
    description: "Voice acting for animated and hosted content.",
    url: "https://storytv.in",
    imageUrl: "",
    useCustomThumbnail: false,
    embed: false,
    size: "80",
    sortOrder: 13,
  },
  {
    id: "seed-testimonial-1",
    section: "testimonials",
    type: "testimonial",
    title: "Aarav Mehta",
    description: "Piyush's voice is exactly what we needed — warm and easy to trust. He got the script right on the first try and sent everything back early. Honestly one of the smoothest collaborations we've had.",
    url: "",
    imageUrl: "",
    useCustomThumbnail: false,
    embed: false,
    size: "standard",
    sortOrder: 14,
    metadata: {
      role: "Creative Lead",
      company: "YouTube Partner",
      rating: 5,
      projectName: "Brand film rollout",
      service: "Voiceover and hosting",
      tags: "Narration, Delivery",
      accent: "linear-gradient(135deg, #0c1445 0%, #2563eb 60%, #60a5fa 100%)",
      quotePreview: "Warm voice, easy to work with, delivered early.",
    },
  },
  {
    id: "seed-testimonial-2",
    section: "testimonials",
    type: "testimonial",
    title: "Sara Khan",
    description: "I sent Piyush a rough brief and he just got it — no back and forth needed. The voice matched our brand better than I expected, and he turned it around fast. Would book him again without thinking twice.",
    url: "",
    imageUrl: "",
    useCustomThumbnail: false,
    embed: false,
    size: "standard",
    sortOrder: 15,
    metadata: {
      role: "Manager",
      company: "Pocket FM",
      rating: 5,
      projectName: "Social campaign package",
      service: "Script + hosting",
      tags: "Campaign, Social",
      accent: "linear-gradient(135deg, #3b0764 0%, #7c3aed 60%, #a78bfa 100%)",
      quotePreview: "Got our brief right away, fast turnaround.",
    },
  },
  {
    id: "seed-testimonial-3",
    section: "testimonials",
    type: "testimonial",
    title: "Rohan Das",
    description: "The way Piyush paced our audio series felt completely natural, like someone telling you a story instead of reading a script. We didn't ask for a single revision — that almost never happens.",
    url: "",
    imageUrl: "",
    useCustomThumbnail: false,
    embed: false,
    size: "standard",
    sortOrder: 16,
    metadata: {
      role: "Content Head",
      company: "Kuku FM",
      rating: 5,
      projectName: "Launch narrative",
      service: "Narration",
      tags: "Narrative, Voice",
      accent: "linear-gradient(135deg, #022c22 0%, #059669 60%, #34d399 100%)",
      quotePreview: "Natural pacing, zero revisions needed.",
    },
  },
  {
    id: "seed-testimonial-4",
    section: "testimonials",
    type: "testimonial",
    title: "Nisha Verma",
    description: "We wanted a voice that sounded confident but still like a real person, not an ad. Piyush nailed that balance, and we actually saw our engagement go up after the campaign launched. He's on our regular roster now.",
    url: "",
    imageUrl: "",
    useCustomThumbnail: false,
    embed: false,
    size: "standard",
    sortOrder: 17,
    metadata: {
      role: "Producer",
      company: "Story TV",
      rating: 5,
      projectName: "Ad campaign voiceover",
      service: "Voice acting",
      tags: "Advertising, Voice",
      accent: "linear-gradient(135deg, #7c2d12 0%, #ea580c 60%, #fbbf24 100%)",
      quotePreview: "Confident but real, engagement went up after launch.",
    },
  },
  {
    id: "seed-testimonial-5",
    section: "testimonials",
    type: "testimonial",
    title: "Vikram Mehta",
    description: "What stood out is how easily Piyush switches styles — serious for a news segment, relaxed for a reel, without it ever feeling forced. He's careful with details too, which saves us a ton of back and forth.",
    url: "",
    imageUrl: "",
    useCustomThumbnail: false,
    embed: false,
    size: "standard",
    sortOrder: 18,
    metadata: {
      role: "Director",
      company: "Radio City",
      rating: 5,
      projectName: "Radio show hosting",
      service: "Hosting",
      tags: "Radio, Hosting",
      accent: "linear-gradient(135deg, #831843 0%, #db2777 60%, #f472b6 100%)",
      quotePreview: "Switches styles easily, careful with details.",
    },
  },

  // ── Featured Projects (Fan Layout) ──
  {
    id: "seed-fan-1",
    section: "fan",
    type: "fan",
    title: "Portal",
    description: "",
    url: "",
    imageUrl: "https://picsum.photos/seed/portal/400/520",
    useCustomThumbnail: false,
    embed: false,
    size: "standard",
    sortOrder: 17,
    metadata: { tag: "Web App", score: 4.9 },
  },
  {
    id: "seed-fan-2",
    section: "fan",
    type: "fan",
    title: "Meridian",
    description: "",
    url: "",
    imageUrl: "https://picsum.photos/seed/meridian/400/520",
    useCustomThumbnail: false,
    embed: false,
    size: "standard",
    sortOrder: 18,
    metadata: { tag: "Brand Identity", score: 4.7 },
  },
  {
    id: "seed-fan-3",
    section: "fan",
    type: "fan",
    title: "Aether",
    description: "",
    url: "",
    imageUrl: "https://picsum.photos/seed/aether/400/520",
    useCustomThumbnail: false,
    embed: false,
    size: "standard",
    sortOrder: 19,
    metadata: { tag: "UI/UX Design", score: 4.8 },
  },
  {
    id: "seed-fan-4",
    section: "fan",
    type: "fan",
    title: "Cascade",
    description: "",
    url: "",
    imageUrl: "https://picsum.photos/seed/cascade/400/520",
    useCustomThumbnail: false,
    embed: false,
    size: "standard",
    sortOrder: 20,
    metadata: { tag: "Mobile App", score: 4.5 },
  },
  {
    id: "seed-fan-5",
    section: "fan",
    type: "fan",
    title: "Vertex",
    description: "",
    url: "",
    imageUrl: "https://picsum.photos/seed/vertex/400/520",
    useCustomThumbnail: false,
    embed: false,
    size: "standard",
    sortOrder: 21,
    metadata: { tag: "Dashboard", score: 4.6 },
  },
];
